import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Donovin's Personal Website",
  description: 'Generated by create next app',
}

/* Think about adding some fonts in this file and 
  perhaps adding a UI library that helps to implement 
  dark and light mode already to make it easier (something that
  isn't too complicated or else it isn't worth the effort). The 
  video explaining fonts that's bookmarked should help. Also learn
  more about tailwind css to create light and dark mode easy and 
  create your own components for the website quick and easy after 
  getting some inspiration looking at other people's personal websites.
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
